#Every changes in MASTER will deploy to marketplase with next patch number
name: deploy

on:
  push:
    branches:
      - master # Your default release branch
        
jobs:
  publish:
    name: list on marketplace
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present

    - name: Deploy Extension
      uses: lannonbr/vsce-action@3.0.0
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.NEW_MARKETPLACE_TOKEN }}
