#Every changes in MASTER will deploy to marketplase with next patch number
name: test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: "Test manual action"
        default: "test"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present

    - name: Commit changes locally
      run: |
        git config user.email "raven03160@gmail.com"
        git config user.name "Veniamin Rakov"
        git add package-lock.json package.json
        git commit -m "Update files by Deploy Action"